# Generated by Django 5.0.1 on 2024-05-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='activo',
            field=models.IntegerField(default=1),
        ),
    ]
